name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build da imagem
        run: docker build -t petmob/peton-api:latest .

      - name: Push para Docker Hub
        run: docker push petmob/peton-api:latest

      - name: Deploy na EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull petmob/peton-api:latest
            docker stop peton-api-container || true
            docker rm peton-api-container || true
            docker run -d \
                --network pet-network \
                -p 5000:80 \
                -e ConnectionStrings__DefaultConnection="${{ secrets.DB_CONNECTION }}" \
                -e JwtSettings__SecretKey="${{ secrets.JWT_SECRET_KEY }}" \
                -e JwtSettings__Issuer="${{ secrets.JWT_ISSUER }}" \
                -e JwtSettings__Audience="${{ secrets.JWT_AUDIENCE }}" \
                -e environmentVariables__EMAIL_USERNAME="${{ secrets.EMAIL_USERNAME }}" \
                -e environmentVariables__EMAIL_PASSWORD="${{ secrets.EMAIL_PASSWORD }}" \
                -e environmentVariables__EMAIL_FROM_NAME="${{ secrets.EMAIL_FROM_NAME }}" \
                -e AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}" \
                -e AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
                -e AWS_BUCKET_NAME="${{ secrets.AWS_BUCKET_NAME }}" \
                -e AWS_REGION="${{ secrets.AWS_REGION }}" \
                --name peton-api-container \
                petmob/peton-api:latest